# Generated by Django 6.0.6 on 2026-06-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paddle_mor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
    ]
