# Generated by Django 6.0.6 on 2026-06-22 20:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


def backfill_webhook_processing_state(apps, schema_editor):
    WebhookEvent = apps.get_model('django_paddle_mor', 'WebhookEvent')

    WebhookEvent.objects.filter(sync_error="").update(
        processing_state='processed',
        processing_attempts=1,
    )
    WebhookEvent.objects.exclude(sync_error="").update(
        processing_state='failed',
        processing_attempts=1,
        last_error_at=models.F('processed_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('django_paddle_mor', '0002_webhookevent_sync_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('secret', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('livemode', models.BooleanField(default=False)),
                ('notification_setting_id', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ('label', 'uuid'),
            },
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processing_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processing_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='dedupe_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='django_paddle_mor.webhookendpoint'),
        ),
        migrations.RunPython(
            backfill_webhook_processing_state,
            migrations.RunPython.noop,
        ),
    ]
