# Generated by Django 6.0.6 on 2026-06-22 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paddle_mor', '0003_webhookendpoint_webhookevent_last_error_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='locale',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='price',
            name='billing_cycle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='price',
            name='catalog_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='price',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='price',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='django_paddle_mor.product'),
        ),
        migrations.AddField(
            model_name='price',
            name='product_external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='price',
            name='quantity',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='price',
            name='tax_mode',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='price',
            name='trial_period',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='price',
            name='unit_price',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='price',
            name='unit_price_amount',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='price',
            name='unit_price_currency_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='address_external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='business_external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='collection_mode',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_billing_period',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='django_paddle_mor.customer'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer_external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='subscription',
            name='first_billed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscription',
            name='management_urls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_billed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='scheduled_change',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='address_external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='billed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='billing_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='billing_period',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='business_external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='collection_mode',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='transaction',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='django_paddle_mor.customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='revised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='django_paddle_mor.subscription'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription_external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
