# Generated by Django 6.0.6 on 2026-06-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paddle_mor', '0004_customer_custom_data_customer_email_customer_locale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscriber_model_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='subscriber_object_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='dedupe_scope',
            field=models.CharField(default='global', max_length=64),
        ),
    ]
