# Generated by django-paddle-mor backfill migration

from django.db import migrations
from django.utils.dateparse import parse_datetime


def _payload_dict(payload, key):
    value = payload.get(key)
    return value if isinstance(value, dict) else {}


def _payload_list(payload, key):
    value = payload.get(key)
    return value if isinstance(value, list) else []


def _payload_str(payload, key):
    value = payload.get(key)
    return value if isinstance(value, str) else ""


def _extract_related_id(payload, *keys):
    for key in keys:
        value = payload.get(key)
        if isinstance(value, str) and value:
            return value
        if isinstance(value, dict):
            identifier = value.get("id")
            if isinstance(identifier, str) and identifier:
                return identifier
    return ""


def _coerce_datetime(value):
    if not isinstance(value, str):
        return None
    return parse_datetime(value)


def backfill_typed_resource_fields(apps, schema_editor):
    Customer = apps.get_model("django_paddle_mor", "Customer")
    Product = apps.get_model("django_paddle_mor", "Product")
    Price = apps.get_model("django_paddle_mor", "Price")
    Subscription = apps.get_model("django_paddle_mor", "Subscription")
    Transaction = apps.get_model("django_paddle_mor", "Transaction")

    for customer in Customer.objects.iterator():
        payload = customer.payload or {}
        customer.email = _payload_str(payload, "email")
        customer.marketing_consent = bool(payload.get("marketing_consent", False))
        customer.locale = _payload_str(payload, "locale")
        customer.custom_data = _payload_dict(payload, "custom_data")
        customer.save(
            update_fields=[
                "email",
                "marketing_consent",
                "locale",
                "custom_data",
                "updated_at",
            ]
        )

    for product in Product.objects.iterator():
        payload = product.payload or {}
        product.description = _payload_str(payload, "description")
        product.tax_category = _payload_str(payload, "tax_category")
        product.image_url = _payload_str(payload, "image_url")
        product.catalog_type = _payload_str(payload, "type")
        product.custom_data = _payload_dict(payload, "custom_data")
        product.save(
            update_fields=[
                "description",
                "tax_category",
                "image_url",
                "catalog_type",
                "custom_data",
                "updated_at",
            ]
        )

    for price in Price.objects.iterator():
        payload = price.payload or {}
        product_external_id = _extract_related_id(payload, "product_id", "product")
        unit_price = _payload_dict(payload, "unit_price")
        price.product_external_id = product_external_id
        price.product = Product.objects.filter(paddle_id=product_external_id).first()
        price.description = _payload_str(payload, "description")
        price.catalog_type = _payload_str(payload, "type")
        price.tax_mode = _payload_str(payload, "tax_mode")
        price.billing_cycle = _payload_dict(payload, "billing_cycle")
        price.trial_period = _payload_dict(payload, "trial_period")
        price.unit_price = unit_price
        price.unit_price_amount = _payload_str(unit_price, "amount")
        price.unit_price_currency_code = _payload_str(unit_price, "currency_code")
        price.quantity = _payload_dict(payload, "quantity")
        price.custom_data = _payload_dict(payload, "custom_data")
        price.save(
            update_fields=[
                "product",
                "product_external_id",
                "description",
                "catalog_type",
                "tax_mode",
                "billing_cycle",
                "trial_period",
                "unit_price",
                "unit_price_amount",
                "unit_price_currency_code",
                "quantity",
                "custom_data",
                "updated_at",
            ]
        )

    for subscription in Subscription.objects.iterator():
        payload = subscription.payload or {}
        customer_external_id = _extract_related_id(payload, "customer_id", "customer")
        subscription.customer = Customer.objects.filter(paddle_id=customer_external_id).first()
        subscription.customer_external_id = customer_external_id
        subscription.address_external_id = _extract_related_id(payload, "address_id", "address")
        subscription.business_external_id = _extract_related_id(payload, "business_id", "business")
        subscription.currency_code = _payload_str(payload, "currency_code")
        subscription.collection_mode = _payload_str(payload, "collection_mode")
        subscription.billing_cycle = _payload_dict(payload, "billing_cycle")
        subscription.current_billing_period = _payload_dict(payload, "current_billing_period")
        subscription.scheduled_change = _payload_dict(payload, "scheduled_change")
        subscription.management_urls = _payload_dict(payload, "management_urls")
        subscription.items = _payload_list(payload, "items")
        subscription.custom_data = _payload_dict(payload, "custom_data")
        subscription.started_at = _coerce_datetime(payload.get("started_at"))
        subscription.first_billed_at = _coerce_datetime(payload.get("first_billed_at"))
        subscription.next_billed_at = _coerce_datetime(payload.get("next_billed_at"))
        subscription.paused_at = _coerce_datetime(payload.get("paused_at"))
        subscription.canceled_at = _coerce_datetime(payload.get("canceled_at"))
        subscription.save(
            update_fields=[
                "customer",
                "customer_external_id",
                "address_external_id",
                "business_external_id",
                "currency_code",
                "collection_mode",
                "billing_cycle",
                "current_billing_period",
                "scheduled_change",
                "management_urls",
                "items",
                "custom_data",
                "started_at",
                "first_billed_at",
                "next_billed_at",
                "paused_at",
                "canceled_at",
                "updated_at",
            ]
        )

    for transaction in Transaction.objects.iterator():
        payload = transaction.payload or {}
        customer_external_id = _extract_related_id(payload, "customer_id", "customer")
        subscription_external_id = _extract_related_id(payload, "subscription_id", "subscription")
        checkout = _payload_dict(payload, "checkout")
        transaction.customer = Customer.objects.filter(paddle_id=customer_external_id).first()
        transaction.subscription = Subscription.objects.filter(
            paddle_id=subscription_external_id
        ).first()
        transaction.customer_external_id = customer_external_id
        transaction.subscription_external_id = subscription_external_id
        transaction.address_external_id = _extract_related_id(payload, "address_id", "address")
        transaction.business_external_id = _extract_related_id(payload, "business_id", "business")
        transaction.discount_external_id = _extract_related_id(payload, "discount_id", "discount")
        transaction.currency_code = _payload_str(payload, "currency_code")
        transaction.origin = _payload_str(payload, "origin")
        transaction.collection_mode = _payload_str(payload, "collection_mode")
        transaction.invoice_id = _payload_str(payload, "invoice_id")
        transaction.invoice_number = _payload_str(payload, "invoice_number")
        transaction.billing_details = _payload_dict(payload, "billing_details")
        transaction.billing_period = _payload_dict(payload, "billing_period")
        transaction.details = _payload_dict(payload, "details")
        transaction.items = _payload_list(payload, "items")
        transaction.payments = _payload_list(payload, "payments")
        transaction.custom_data = _payload_dict(payload, "custom_data")
        transaction.checkout_url = _payload_str(checkout, "url")
        transaction.billed_at = _coerce_datetime(payload.get("billed_at"))
        transaction.revised_at = _coerce_datetime(payload.get("revised_at"))
        transaction.save(
            update_fields=[
                "customer",
                "subscription",
                "customer_external_id",
                "subscription_external_id",
                "address_external_id",
                "business_external_id",
                "discount_external_id",
                "currency_code",
                "origin",
                "collection_mode",
                "invoice_id",
                "invoice_number",
                "billing_details",
                "billing_period",
                "details",
                "items",
                "payments",
                "custom_data",
                "checkout_url",
                "billed_at",
                "revised_at",
                "updated_at",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("django_paddle_mor", "0005_customer_subscriber_model_label_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_typed_resource_fields, migrations.RunPython.noop),
    ]
